[tool.poetry]
authors = ["Neeraj Shah <resistics@outlook.com>"]
description = "Python package for processing magnetotelluric data"
license = "MIT"
name = "resistics"
version = "0.0.7"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
numpy = "1.20.2"
scipy = "1.6.2"
pandas = "1.2.3"
lttbc = "0.2.0"
attotime = "0.2.3"
plotly = "4.14.3"

[tool.poetry.dev-dependencies]
matplotlib="3.4.1"
pytest="6.2.3"
pytest-cov="2.11.1"
pytest-html="3.1.1"
mypy="0.812"
darglint="1.8.0"
flake8="3.9.0"
flakehell="0.9.0"
black="20.8b1"
safety="1.10.3"
Sphinx="3.5.3"
furo=">=2021.3.20b30"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --cov --cov-report html --cov-report xml --junitxml=artifacts/test.xml --html=artifacts/test_html/report.html"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS"
minversion = "6.0"
testpaths = ["resistics", "tests"]

[tool.coverage.paths]
source = ["resistics"]

[tool.coverage.run]
branch = true
source = ["resistics"]

[tool.coverage.report]
show_missing = true

[tool.coverage.html]
directory = "artifacts/coverage_html"

[tool.coverage.xml]
output = "artifacts/coverage.xml"

[tool.flakehell]
docstring-convention = "numpy"
format = "grouped"
max_line_length = 88
show_source = true

[tool.flakehell.plugins]
darglint = ["+*"]
"flake8-*" = ["+*"]
mccabe = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]

[tool.flakehell.exceptions."tests/"]
flake8-bandit = ["-S101"]

[tool.black]
line-length = 88
target-version = ["py39"]
