# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry --version
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report
      - name: Lint with flake8
        run: poetry run flake8 resistics
        if: matrix.platform == 'ubuntu-latest' && matrix.python-version == 3.9
      - name: Check docstrings
        run: poetry run darglint resistics
        if: matrix.platform == 'ubuntu-latest' && matrix.python-version == 3.9
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        if: ${{ github.ref == 'refs/heads/master' }} && matrix.platform == 'ubuntu-latest' && matrix.python-version == 3.9
        with:
          fail_ci_if_error: true
